### ISSUE TITLE
check handling of year 0

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/JDNConvertibleCalendar#3]
fourmilab.ch uses the following convention: 

> While one can't properly speak of “Gregorian dates” prior to the adoption of the calendar in 1582, the calendar can be extrapolated to prior dates. In doing so, this implementation uses the convention that the year prior to year 1 is year 0. This differs from the Julian calendar in which there is no year 0—the year before year 1 in the Julian calendar is year −1. The date December 30th, 0 in the Gregorian calendar corresponds to January 1st, 1 in the Julian calendar.

<http://fourmilab.ch/documents/calendar/>

When doing dealing with `CalendarDate`, we have to take that into account (it matters in which calendar we are).

**Comment by tobiasschweizer** [comment]
I think here it is done differently: http://keisan.casio.com/exec/system/1227779487

**Comment by tobiasschweizer** [comment]
see also https://bowie.gsfc.nasa.gov/time/julian.html

**Comment by benjamingeer** [comment]
My interpretation of this question: https://github.com/dhlab-basel/Knora/issues/578
