### ISSUE TITLE
Support for Hijri/Islamic calendar

### ISSUE THREAD

**Issue by AlQuraian** [dhlab-basel/JDNConvertibleCalendar#5]
Thank you for this promising project and for the integration with Angular. It would be great if you add support to the Hijri or Islamic calendar.

If there's a way I can help please give us some guidance.

Thanks again.

**Comment by tobiasschweizer** [comment]
Hi

We definitely plan to add support for the Islamic calendar.

We need to make another subclass of `JDNConvertibleCalendar` (in `JDNConvertibleCalendarModule `) and implement the conversions from and to Julian Day (in `JDNConvertibleConversionModule `). 

It would be great if you could take part in the reviewing process of that upcoming PR.

Thanks a lot!

Tobias

**Comment by tobiasschweizer** [comment]
@AlQuraian There is an open PR #10 now supporting the conversion from and to Islamic calendar dates.
